# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    
    - name: Build with Maven
      run: mvn clean package
      
    - name: Upload Build to server and restart app
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
        chmod 400 private_key
        mkdir ~/.ssh
        ssh-keyscan -H ${{secrets.SERVER_HOST}} > ~/.ssh/known_hosts
        ssh -i private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} <<-'ENDSSH'
          sudo rm hx-events.jar
          sudo rm /var/spring-apps/hx-events.jar
        ENDSSH
        scp -i private_key target/hx-events.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/
        ssh -i private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} <<-'ENDSSH'
          sudo systemctl stop hx-events.service
          sudo cp hx-events.jar /var/spring-apps/hx-events.jar
          sudo chown azureuser:azureuser /var/spring-apps/hx-events.jar
          sudo chmod 500 /var/spring-apps/hx-events.jar
          sudo systemctl start hx-events.service
        ENDSSH

